name: img_picker_platform_interface
description: A common platform interface for the img_picker plugin.
repository: https://github.com/saravanakumar007/image_picker_platform_interface
issue_tracker: https://github.com/saravanakumar007/image_picker_platform_interface/issues
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 1.0.0

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  cross_file: ^0.3.1+1
  flutter:
    sdk: flutter
  http: ">=0.13.0 <2.0.0"
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - image-picker
  - files
  - file-selection
